/**
 * Reads SKILL.md files and generates a TypeScript module
 * with skill content as string constants.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = path.resolve(__dirname, "../skills");
const OUTPUT = path.resolve(__dirname, "../src/skill-content.ts");

const SKILL_NAMES = ["explore", "test", "debug", "coverage"];

let output = "// Auto-generated by scripts/embed-skills.js — do not edit\n\n";
output += "export const SKILLS: Record<string, string> = {\n";

for (const name of SKILL_NAMES) {
  const filePath = path.join(SKILLS_DIR, name, "SKILL.md");
  const content = fs.readFileSync(filePath, "utf-8");
  // Strip YAML frontmatter
  const stripped = content.replace(/^---[\s\S]*?---\n*/, "");
  // Escape backticks and ${} for template literal
  const escaped = stripped.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  output += `  ${name}: \`${escaped}\`,\n`;
}

output += "};\n";

fs.writeFileSync(OUTPUT, output);
console.log(`Generated ${OUTPUT} with ${SKILL_NAMES.length} skills`);
