// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: godotplay.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GodotPlay.Protocol {
  public static partial class GodotPlayService
  {
    static readonly string __ServiceName = "godotplay.GodotPlayService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.Empty> __Marshaller_godotplay_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.PingResponse> __Marshaller_godotplay_PingResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.PingResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SceneTreeRequest> __Marshaller_godotplay_SceneTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SceneTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SceneTreeResponse> __Marshaller_godotplay_SceneTreeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SceneTreeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.NodeQuery> __Marshaller_godotplay_NodeQuery = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.NodeQuery.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.NodeList> __Marshaller_godotplay_NodeList = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.NodeList.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.NodeRef> __Marshaller_godotplay_NodeRef = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.NodeRef.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.PropertyMap> __Marshaller_godotplay_PropertyMap = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.PropertyMap.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.ActionResult> __Marshaller_godotplay_ActionResult = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.ActionResult.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.ScreenshotRequest> __Marshaller_godotplay_ScreenshotRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.ScreenshotRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.ScreenshotResponse> __Marshaller_godotplay_ScreenshotResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.ScreenshotResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.TypeRequest> __Marshaller_godotplay_TypeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.TypeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SetPropertyRequest> __Marshaller_godotplay_SetPropertyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SetPropertyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.LoadSceneRequest> __Marshaller_godotplay_LoadSceneRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.LoadSceneRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SceneInfo> __Marshaller_godotplay_SceneInfo = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SceneInfo.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.WaitRequest> __Marshaller_godotplay_WaitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.WaitRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SignalWaitRequest> __Marshaller_godotplay_SignalWaitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SignalWaitRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.SignalData> __Marshaller_godotplay_SignalData = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.SignalData.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.EventFilter> __Marshaller_godotplay_EventFilter = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.EventFilter.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::GodotPlay.Protocol.GameEvent> __Marshaller_godotplay_GameEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::GodotPlay.Protocol.GameEvent.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.PingResponse> __Method_Ping = new grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.PingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_godotplay_Empty,
        __Marshaller_godotplay_PingResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.Empty> __Method_Shutdown = new grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Shutdown",
        __Marshaller_godotplay_Empty,
        __Marshaller_godotplay_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.SceneTreeRequest, global::GodotPlay.Protocol.SceneTreeResponse> __Method_GetSceneTree = new grpc::Method<global::GodotPlay.Protocol.SceneTreeRequest, global::GodotPlay.Protocol.SceneTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSceneTree",
        __Marshaller_godotplay_SceneTreeRequest,
        __Marshaller_godotplay_SceneTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.NodeQuery, global::GodotPlay.Protocol.NodeList> __Method_FindNodes = new grpc::Method<global::GodotPlay.Protocol.NodeQuery, global::GodotPlay.Protocol.NodeList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FindNodes",
        __Marshaller_godotplay_NodeQuery,
        __Marshaller_godotplay_NodeList);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.PropertyMap> __Method_GetNodeProperties = new grpc::Method<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.PropertyMap>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetNodeProperties",
        __Marshaller_godotplay_NodeRef,
        __Marshaller_godotplay_PropertyMap);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.ActionResult> __Method_Click = new grpc::Method<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.ActionResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Click",
        __Marshaller_godotplay_NodeRef,
        __Marshaller_godotplay_ActionResult);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.ScreenshotRequest, global::GodotPlay.Protocol.ScreenshotResponse> __Method_TakeScreenshot = new grpc::Method<global::GodotPlay.Protocol.ScreenshotRequest, global::GodotPlay.Protocol.ScreenshotResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TakeScreenshot",
        __Marshaller_godotplay_ScreenshotRequest,
        __Marshaller_godotplay_ScreenshotResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.TypeRequest, global::GodotPlay.Protocol.ActionResult> __Method_Type = new grpc::Method<global::GodotPlay.Protocol.TypeRequest, global::GodotPlay.Protocol.ActionResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Type",
        __Marshaller_godotplay_TypeRequest,
        __Marshaller_godotplay_ActionResult);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.SetPropertyRequest, global::GodotPlay.Protocol.ActionResult> __Method_SetProperty = new grpc::Method<global::GodotPlay.Protocol.SetPropertyRequest, global::GodotPlay.Protocol.ActionResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SetProperty",
        __Marshaller_godotplay_SetPropertyRequest,
        __Marshaller_godotplay_ActionResult);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.LoadSceneRequest, global::GodotPlay.Protocol.ActionResult> __Method_LoadScene = new grpc::Method<global::GodotPlay.Protocol.LoadSceneRequest, global::GodotPlay.Protocol.ActionResult>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LoadScene",
        __Marshaller_godotplay_LoadSceneRequest,
        __Marshaller_godotplay_ActionResult);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.SceneInfo> __Method_GetCurrentScene = new grpc::Method<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.SceneInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCurrentScene",
        __Marshaller_godotplay_Empty,
        __Marshaller_godotplay_SceneInfo);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.WaitRequest, global::GodotPlay.Protocol.NodeRef> __Method_WaitForNode = new grpc::Method<global::GodotPlay.Protocol.WaitRequest, global::GodotPlay.Protocol.NodeRef>(
        grpc::MethodType.Unary,
        __ServiceName,
        "WaitForNode",
        __Marshaller_godotplay_WaitRequest,
        __Marshaller_godotplay_NodeRef);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.SignalWaitRequest, global::GodotPlay.Protocol.SignalData> __Method_WaitForSignal = new grpc::Method<global::GodotPlay.Protocol.SignalWaitRequest, global::GodotPlay.Protocol.SignalData>(
        grpc::MethodType.Unary,
        __ServiceName,
        "WaitForSignal",
        __Marshaller_godotplay_SignalWaitRequest,
        __Marshaller_godotplay_SignalData);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::GodotPlay.Protocol.EventFilter, global::GodotPlay.Protocol.GameEvent> __Method_SubscribeEvents = new grpc::Method<global::GodotPlay.Protocol.EventFilter, global::GodotPlay.Protocol.GameEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeEvents",
        __Marshaller_godotplay_EventFilter,
        __Marshaller_godotplay_GameEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GodotPlay.Protocol.GodotplayReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GodotPlayService</summary>
    [grpc::BindServiceMethod(typeof(GodotPlayService), "BindService")]
    public abstract partial class GodotPlayServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.PingResponse> Ping(global::GodotPlay.Protocol.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.Empty> Shutdown(global::GodotPlay.Protocol.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.SceneTreeResponse> GetSceneTree(global::GodotPlay.Protocol.SceneTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.NodeList> FindNodes(global::GodotPlay.Protocol.NodeQuery request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.PropertyMap> GetNodeProperties(global::GodotPlay.Protocol.NodeRef request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.ActionResult> Click(global::GodotPlay.Protocol.NodeRef request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.ScreenshotResponse> TakeScreenshot(global::GodotPlay.Protocol.ScreenshotRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Interactions
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.ActionResult> Type(global::GodotPlay.Protocol.TypeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.ActionResult> SetProperty(global::GodotPlay.Protocol.SetPropertyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Navigation
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.ActionResult> LoadScene(global::GodotPlay.Protocol.LoadSceneRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.SceneInfo> GetCurrentScene(global::GodotPlay.Protocol.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Waiting
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.NodeRef> WaitForNode(global::GodotPlay.Protocol.WaitRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::GodotPlay.Protocol.SignalData> WaitForSignal(global::GodotPlay.Protocol.SignalWaitRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Event streaming
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SubscribeEvents(global::GodotPlay.Protocol.EventFilter request, grpc::IServerStreamWriter<global::GodotPlay.Protocol.GameEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(GodotPlayServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping)
          .AddMethod(__Method_Shutdown, serviceImpl.Shutdown)
          .AddMethod(__Method_GetSceneTree, serviceImpl.GetSceneTree)
          .AddMethod(__Method_FindNodes, serviceImpl.FindNodes)
          .AddMethod(__Method_GetNodeProperties, serviceImpl.GetNodeProperties)
          .AddMethod(__Method_Click, serviceImpl.Click)
          .AddMethod(__Method_TakeScreenshot, serviceImpl.TakeScreenshot)
          .AddMethod(__Method_Type, serviceImpl.Type)
          .AddMethod(__Method_SetProperty, serviceImpl.SetProperty)
          .AddMethod(__Method_LoadScene, serviceImpl.LoadScene)
          .AddMethod(__Method_GetCurrentScene, serviceImpl.GetCurrentScene)
          .AddMethod(__Method_WaitForNode, serviceImpl.WaitForNode)
          .AddMethod(__Method_WaitForSignal, serviceImpl.WaitForSignal)
          .AddMethod(__Method_SubscribeEvents, serviceImpl.SubscribeEvents).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GodotPlayServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.PingResponse>(serviceImpl.Ping));
      serviceBinder.AddMethod(__Method_Shutdown, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.Empty>(serviceImpl.Shutdown));
      serviceBinder.AddMethod(__Method_GetSceneTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.SceneTreeRequest, global::GodotPlay.Protocol.SceneTreeResponse>(serviceImpl.GetSceneTree));
      serviceBinder.AddMethod(__Method_FindNodes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.NodeQuery, global::GodotPlay.Protocol.NodeList>(serviceImpl.FindNodes));
      serviceBinder.AddMethod(__Method_GetNodeProperties, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.PropertyMap>(serviceImpl.GetNodeProperties));
      serviceBinder.AddMethod(__Method_Click, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.NodeRef, global::GodotPlay.Protocol.ActionResult>(serviceImpl.Click));
      serviceBinder.AddMethod(__Method_TakeScreenshot, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.ScreenshotRequest, global::GodotPlay.Protocol.ScreenshotResponse>(serviceImpl.TakeScreenshot));
      serviceBinder.AddMethod(__Method_Type, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.TypeRequest, global::GodotPlay.Protocol.ActionResult>(serviceImpl.Type));
      serviceBinder.AddMethod(__Method_SetProperty, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.SetPropertyRequest, global::GodotPlay.Protocol.ActionResult>(serviceImpl.SetProperty));
      serviceBinder.AddMethod(__Method_LoadScene, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.LoadSceneRequest, global::GodotPlay.Protocol.ActionResult>(serviceImpl.LoadScene));
      serviceBinder.AddMethod(__Method_GetCurrentScene, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.Empty, global::GodotPlay.Protocol.SceneInfo>(serviceImpl.GetCurrentScene));
      serviceBinder.AddMethod(__Method_WaitForNode, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.WaitRequest, global::GodotPlay.Protocol.NodeRef>(serviceImpl.WaitForNode));
      serviceBinder.AddMethod(__Method_WaitForSignal, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GodotPlay.Protocol.SignalWaitRequest, global::GodotPlay.Protocol.SignalData>(serviceImpl.WaitForSignal));
      serviceBinder.AddMethod(__Method_SubscribeEvents, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GodotPlay.Protocol.EventFilter, global::GodotPlay.Protocol.GameEvent>(serviceImpl.SubscribeEvents));
    }

  }
}
#endregion
